# Generated by Django 5.2.4 on 2026-01-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='companies',
            new_name='company',
        ),
    ]
