# Generated by Django 5.2.4 on 2026-01-31 02:55

from django.db import migrations

def seed_global_categories(apps,schemaeditor):
        ExpenseCategory = apps.get_model('backend','ExpenseCategory')

        default_categories = ["Delivery","Miscellaneous","Travel & Transportation","Repair & Maintenance","Utilities","Marketing","Bank Fees","Salaries","Rent"]

        for cat_name in default_categories:
            ExpenseCategory.objects.get_or_create(name = cat_name,company= None,is_global=True)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_global_categories)
    ]
