# Generated by Django 5.2.4 on 2026-01-30 09:34

from django.db import migrations

def create_global_categories(apps,schema_editor):
    Company = apps.get_model("backend","Company")
    ExpenseCategory = apps.get_model("backend","ExpenseCategory")

    global_company,created = Company.objects.get_or_create(name="Global")

    default_categories = ["Delivery","Miscellaneous","Travel & Transportation","Repair & Maintenance","Utilities","Marketing","Salary","Rent"]

    for cat_name in default_categories:
        ExpenseCategory.objects.get_or_create(name=cat_name,company=global_company,defaults = {"is_global":True})

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_global_categories),
    ]
