# Generated by Django 5.2.4 on 2026-01-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_seed_global_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingamount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerRemainingAmount', to='backend.customer'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('name',), name='unique-global-category'),
        ),
    ]
