# Generated by Django 5.2.4 on 2026-01-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_customer_name_alter_expensecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='backend.expensecategory'),
            preserve_default=False,
        ),
    ]
